### ISSUE TITLE
Element type is invalid: expected a string

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#75] opened 2019-06-13 07:56 UTC
https://sentry.io/organizations/big-neon-5x/issues/1053354917/?project=1407235&query=is%3Aunresolved&statsPeriod=14d
Check the render method of AuthIndex

**Comment by mileTadic1994** [comment] 2019-06-25 13:43
Can you provide me with more info about this. Because when I try to access this link it redirects me to login every time, even after I login.

**Comment by Krakaw** [comment] 2019-07-26 11:41
Closing until we can reproduce

**Closed by Krakaw** 2019-07-26 11:41 UTC
Labels: bug, move to bug backlog
